src/lex-web-ui-loader/js/lib/iframe-component-loader.js
chat bot is always placed to the body. developer is not able to change position to a particular element
=> Not able to configure the chatbot position

lex-web-ui/src/components/InputContainer.vue, lex-web-ui/src/components/ToolbarContainer.vue, lex-web-ui/src/store/actions.js
*Issue #, if available:* n/a
*Description of changes:* bug fixes
=> Feature connect live chat chris bugfixes

lex-web-ui/src/components/LexWeb.vue
=> Check for required config values (region & poolId) - improved

lex-web-ui/package-lock.json
Bump minimist from 1.2.5 to 1.2.6 in /lex-web-ui
=> Bump minimist from 1.2.5 to 1.2.6 in /lex-web-ui

CHANGELOG.md, package.json
Update version number and changelog
=> fix: update version number and changelog date

lex-web-ui/src/components/ToolbarContainer.vue
Position image if available and toolbar title if available with left margins of 0 to allow better fit of toolbar buttons that appear on right edge of toolbar. 
=> Set better positioning of image and toolbar title.

CHANGELOG.md, lex-web-ui/package.json, package.json
=> Feature/release v0.19.7

templates/codebuild-deploy.yaml
To prepare for rollout of new S3 bucket defaults.
=> Remove ACL and use bucket policy per S3 guidelines

CHANGELOG.md, lex-web-ui/package.json, package.json
=> Update package versions and ChangeLog for release.

CHANGELOG.md, lex-web-ui/src/components/Message.vue, src/lex-web-ui-loader/js/defaults/dependencies.js
=> Rollback dependency changes & update timepicker

templates/codebuild-deploy.yaml
=> Fix issue with Cloutfront logging bucket

templates/codebuild-deploy.yaml
=> Hotfix for issue with Cloudfront standard logging on new S3 buckets

CHANGELOG.md, lex-web-ui/package.json, package.json
=> Update changelog and version for release

README-connect-live-chat.md, lex-web-ui/README.md, src/initiate-chat-lambda/index.js
=> Reduce chat duration & add documentation

README-connect-live-chat.md, README.md, src/website/index.html, templates/cognito.yaml
=> Cognito updates & documentation clarifications

README-connect-live-chat.md, lex-web-ui/README.md
=> Add notes about default TLS configurations

lex-web-ui/README.md, src/website/index.html
=> Fix issue with voice & clarify session storage doc

templates/codebuild-deploy.yaml, templates/cognito.yaml, templates/master.yaml
=> Add domain based auto-registration & auto-add parent origin to CSP header

templates/codebuild-deploy.yaml
=> Hotfix for child template not having default value

CHANGELOG.md, lex-web-ui/package.json, package.json
=> Release updates

lex-web-ui/package-lock.json, lex-web-ui/package.json, package-lock.json, package.json, templates/master-pipeline.yaml, templates/master.yaml
=> Fix yaml files & lower node version

CHANGELOG.md, lex-web-ui/package.json, package.json
=> Release 0.20.4 updates

templates/codebuild-deploy.yaml
=> Remove bad reference to  live chat on Rest stack

src/initiate-chat-lambda/index.js, src/streaming-lambda/index.js, templates/cognito.yaml, templates/restapi.yaml, templates/streaming-support.yaml
Node 14 is going out of support for Lambda so these changes update to v18, which requires reworking the lambda functions themselves for JS SDK v3 compatibility.
=> Upgrade to Node 18 and modify Lambdas for SDK v3

CHANGELOG.md, lex-web-ui/package.json, package.json
=> v0.21.0 release changes

templates/codebuild-deploy.yaml
=> Fix outputs from streaming

CHANGELOG.md, lex-web-ui/package.json, package.json
=> Update changelog & version number

package-lock.json, package.json, webpack.config.js
=> Fix webpack issue with 'vm'

templates/codebuild-deploy.yaml
=> Fix issue with codebuild template

README-connect-live-chat.md, lex-web-ui/src/store/actions.js, lex-web-ui/src/store/mutations.js, lex-web-ui/src/store/talkdesk-live-chat-handlers.js
Provides a mechanism to integrate and TalkDesk for live agent chat via websocket connection to a preconfigured TalkDesk endpoint. Blog post explaining full integration steps will be included.
=> TalkDesk integration with Lex Web UI

build/upload-bootstrap.sh
=> Remove acl option for s3 cp commands

templates/coderepo.yaml
#673 
* Upgrade build agent image to AL2
* Fix bug with missing installing dependencies step
=> Fix issue with initiating CodeCommit repo

lex-web-ui/package-lock.json, lex-web-ui/package.json, package-lock.json, templates/codebuild-deploy.yaml, templates/coderepo.yaml, templates/cognitouserpoolconfig.yaml, templates/custom-resources/requirements.txt, templates/lexbot.yaml, templates/master.yaml, templates/pipeline.yaml
=> Upgrade to python3.10 and latest boto3

templates/custom-resources/requirements.txt
=> roll back boto3 upgrade

README-css-style.md, lex-web-ui/vue.config.js
=> Fix some CSS documentation and update build for Windows machines

templates/lexbot.yaml, templates/master.yaml
=> Fix template errors

build/Makefile
Hopefully temporary, but the boto3 version does still not have the latest Q updates
=> Fix layer uploading to bucket for build

lex-web-ui/vue.config.js
=> Fix deploymnet script

lex-web-ui/package-lock.json, package-lock.json
=> Package updates

src/website/index.html, templates/codebuild-deploy.yaml
=> Fix S3 cleanup to not delete on update

config/utils/merge-config.js, lex-web-ui/src/config/index.js, templates/codebuild-deploy.yaml, templates/master.yaml
- Adds streaming support to chat client
=> Feature/qnabot v7.0.0 stream

lex-web-ui/package-lock.json, lex-web-ui/package.json, lex-web-ui/src/store/actions.js, package-lock.json, templates/master.yaml, templates/streaming-support.yaml
=> Update dependencies and add auth to streaming websocket

lex-web-ui/src/store/getters.js
*Issue #782 *
Update getters.js to handle empty and/or missing transcriptRedactRegex configuration value. 
=> Revise handling of connect transcript redaction.
