src/website/index.html

This extra comma prevented index.html from rendering. I viewed with IE11 and Chrome 53 and this syntax error prevented the page from rendering. Removing it fixed the problem locally so I thought a pull request should be made to fix it permanently for others.

Remove extra comma from function parameter list.

---

CHANGELOG.md
package-lock.json
package.json
templates/codebuild-deploy.yaml

fix issue #53

---

lex-web-ui/src/components/ResponseCard.vue

Added a title exists or not before doing an trim on the title string. There is possibility that title can be null and response card won't render in that particular case because doing trim on null.
*Issue #185 :*
This is not an exact issue, but while checking on above issue caught my eyes on it.
There is possibility that response card title can be **null** and the response card won't render in that particular case because doing trim on **null**.

Added a response card title exists check before doing title trim

---

templates/master-pipeline.yaml

*Issue #, if available:* n/a
When deploying via the Code Pipeline method, the CognitoUserPoolId and CognitoAppUserPoolClientId are required, even if you ask to use an existing Cognito Pool.
This change subs in empty strings in this case.

Made CognitoAppUserPoolClientId and CognitoUserPoolId optional

---

lex-web-ui/src/components/MessageList.vue
lex-web-ui/src/components/MessageLoading.vue

Issue #, if available:
The loading message is sometimes not displayed as it's below the message list scroll line
Description of changes:
added watching the computed loading value
only offset the message list scroll position if the last message is not a loading message

fixed displaying of loading message

---

lex-web-ui/src/store/actions.js

If no initialText is set in config then the UI can show a blank message - this is more obvious when an avatar image is set for the bot as all that is displayed is the avatar with no message
Check that initialText has a value before pushing an initial message to the message list.

Check that initialText has a value, before pushing to message list

---

lex-web-ui/src/components/LexWeb.vue

if LexruntimeV2 is expected but can't be instantiated due to config issues missing region or cognito.poolId then it fails silently
if no config.region set, fall back to checking config.cognito.region
throw an error if LexruntimeV2 is unable to be instantiated. explaining if there's no region, poolId or config set

Error in LexruntimeV2 can't be instantiated due to config issues

---

templates/codebuild-deploy.yaml
templates/pipeline.yaml

Change lexwebui cloudfront distribution templates to use managed CachePolicyId and OriginRequestPolicyId. This establishes correct policies to cache origin headers properly from browsers notably safari and chrome. 
This addresses a problem where a subsequent reload of a page hosting lexwebui via iframe fails with CORS error when re-loading the lex-web-ui-loader-config.json file. 

Switch lexwebui cloudfront distribution to use managed CachePolicyId and OriginRequestPolicyId.

---

lex-web-ui/src/components/LexWeb.vue
lex-web-ui/src/store/actions.js
lex-web-ui/src/store/state.js
src/lex-web-ui-loader/js/lib/iframe-component-loader.js

Updating parent calls to control the tease bubble by providing the parent control over the entire tease bubble feature being enabled/disabled, rather than just showing or hiding the bubble.

Adding framework to programatically control tease bubble

---

lex-web-ui/src/store/live-chat-handlers.js
templates/master-pipeline.yaml
templates/pipeline.yaml

*Issue #, if available:*  N/A
Discovered that the CloudFormation template to deploy a CI/CD Pipeline for Lex-Web-UI would fail on the attempt to create the Pipeline resource.  This was because the Pipeline template had Properties for Lex v1 BotName which required a minimum of 2 characters so deploying the Pipeline expected a value even if deploying for a Lex v2 environment.  The master-pipeline.yaml was updated to remove the IF statement in the Pipeline resource since it wasn't needed after fixing the BotName and BotAlias properties in the Pipeline.yaml file.  There was also an issue creating the RestAPI within the Pipeline.yaml because the path to the CloudFormation template for the RestAPI.yaml was not correct so the master-pipeline.yaml was updated to add a …

Fixes for cfn templates and livechat

---

lex-web-ui/src/lib/lex/client.js

This PR only covers handling the new ElicitIntent dialogAction type response, which does not have some expected properties on the sessionState object and blows up Lex Web UI

Add in response checking to prevent undefined errors on ElicitIntent dialogType responses

---

src/lex-web-ui-loader/js/lib/loginutil.js

*#487*
**
to fix this issue, I just added timeout function before checking if the session is valid or not this timeout function makes sure that the token is fetched properly before the session validation. I don't know if this is the ideal way to do this, so any alternative suggestions will be helpful.

fix for max login tries exceeded error

---

lex-web-ui/src/components/Message.vue
src/lex-web-ui-loader/js/defaults/dependencies.js

This PR cleans up an issue that occurred when trying to render the DateTime picker with multiple language locales in the bot, also clean up the logic a bit to remove complexity and add readability.
Also addresses an issue where certain parts of the ListPicker were not rendering because the loader dependencies were very old and certain veutify components were not supported

Clean up date logic & bump vuetify dependencies

---

lex-web-ui/src/store/actions.js

- ###### co-fix-dupe of https://github.com/aws-samples/aws-lex-web-ui/pull/537 minus `dist` for the greater good
In `lex-web-ui/src/store/actions.js`, there is a reference to `context.state.isPostTextRetry` but `isPostTextRetry` should be accessed via `context.state.lex.isPostTextRetry` instead.
In the current state, the block `if (context.state.isPostTextRetry) {` is never accessed because `context.state.isPostTextRetry` is undefined.
Please modify PR to your convenience if needed.
Thanks! 
cc @tonystrawberry → hope you don't mind 🫡

fix: wrong reference to `isPostTextRetry`

---

lex-web-ui/src/components/MessageLoading.vue
lex-web-ui/src/store/actions.js
lex-web-ui/src/store/getters.js
lex-web-ui/src/store/mutations.js
lex-web-ui/src/store/state.js

N/A
To support streaming-like feature. I have added a web socket client after initializing LexClient and get sessionId as a key and connect to API Gateway web socket API. 
I also leverage allowStreamingResponses property to determine whether enable web socket client or not. 

Init commit for streaming support

---

lex-web-ui/vue.config.js
src/lex-web-ui-loader/js/lib/iframe-component-loader.js
webpack.config.js

This PR picks up some red errors when running  `npm run build` at root, `npm run build-dist` at child, and `npm run dev` at either, which exposed the anomalies via stack trace in debug/dev mode.
1.  Define `isProd`  to correctly map `env`
```sh
> aws-lex-web-ui@0.20.2 build-dev
> webpack --mode development
env { WEBPACK_BUNDLE: true, WEBPACK_BUILD: true }
(env.production === true) false
env.production undefined
```
2.  Refactor/fix [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) v5 signature in`webpack.config.js` Note: `optimization.minimize: false` removes License.txt outputs [`file].LICENSE.txt[query]`](https://webpack.js.org/plugins/terser-webpack-plugin/#filename) without [plugging …

Fix/config: bundler and loader syntax variety

---

README-streaming-responses.md
config/base.env.js
lex-web-ui/.browserslistrc
lex-web-ui/package.json
lex-web-ui/src/components/InputContainer.vue
lex-web-ui/src/components/Message.vue
lex-web-ui/src/config/index.js
lex-web-ui/src/lex-web-ui.js
package.json
src/config/default-lex-web-ui-loader-config.json
templates/codebuild-deploy.yaml
templates/streaming-support.yaml

This update is designed to make streaming more flexible in scenarios where the bot is handling both streaming and non-streaming conversations. Turning streaming on at the Web UI will now trigger session attributes containing the dynamo table and API Gateway endpoint information, so fulfillment Lambdas can look for those parameters and decide whether the response needs to be streamed.
Other small changes
- Bring the Web UI up to speed on Node/NPM versions 
- Change the browser targets for webpack.
- Make the copy function/icon a toggle controlled by a config property and center it to align with the feedback buttons.

Updates for more flexible streaming options

---

lex-web-ui/README.md
lex-web-ui/src/components/Message.vue

Add carousel support & fix readme for web ui local dev

---

templates/master-pipeline.yaml
templates/pipeline.yaml

Issue #, if available:
https://github.com/aws-samples/aws-lex-web-ui/issues/665
Description of changes:

Fix bugs with pipeline templates

---

src/qbusiness-lambda/index.py

Description of changes:
This pull request adds the Python lambda code to enable integration with the QBusiness Identity Center (IDC) as well as caching of credentials in DynamoDB.
The following additions were made:
- Added code to call create_token_with_iam to generate a session based on assuming an IAM role with permissions to QBusiness. This allows the application to integrate with IDC and generate temporary security credentials that can be reused to call the QBusiness chatsync operation.
- Added a reference to a new DynamoDB table to cache credentials generated via the IDC until their expiration time, including encryption and decryption of the credentials object using KMS. Because the passed JWT can only be used once unless refreshed, caching allows the plugin to re-use the generated …

QBusiness IDC Integration

---

lex-web-ui/src/config/index.js
templates/codebuild-deploy.yaml
templates/master.yaml

- adds StreamingWebSocketEndpoint and StreamingDynamoDbTable as optional CF parameters to override existing ones that are created when AllowStreamingResponses is True

streaming endpoint support for qnabot

---

lex-web-ui/src/lib/lex/client.js

Fix send to be correct version
